name: zagel_news_app
description: A new Flutter project for news app to practice the clean architecture, tdd , testing.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  # Service Locator
  get_it: ^7.2.0
  # Bloc pattern for state management
  flutter_bloc: ^8.0.1
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  dio: ^4.0.6
  # Local storage
  get_storage: ^2.0.3

  # for code documentation
#  dartdoc: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  lint: ^1.8.2
  integration_test:
    sdk: flutter
  # testing stuff
  mocktail: ^0.3.0


flutter:

  uses-material-design: true