name: zagel_news_app
description: A new Flutter project for news app to practice the clean architecture, tdd , testing.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  # Service Locator
  get_it: ^7.2.0
  # state management
  flutter_bloc: ^8.0.1
  flutter_riverpod: ^2.1.3
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  dio: ^4.0.6
  # Local storage
  get_storage: ^2.0.3
  # connection to the internet
  data_connection_checker_tv: ^0.3.5-nullsafety
  # Local storage
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9


dev_dependencies:
  # testing stuff
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  # code lints
  flutter_lints: ^1.0.4
  lint: ^1.8.2




flutter:

  uses-material-design: true